package com.sliit.se2030.mall.config;

import java.math.BigDecimal;
import java.util.List;

/**
 * Demo catalogue used by DataSeedConfig: one themed shop per seeded merchant
 * (shop 1 belongs to merc1@mail.com, shop 2 to merc2@mail.com, ...), each with
 * its own category and a dozen products.
 *
 * Product photos are hotlinked from DummyJSON's public demo-product CDN
 * (https://dummyjson.com/docs/products), so every image matches its product.
 * Prices are in rupees.
 *
 * Shop logos are simple SVGs bundled in static/images/logos (the shops are made
 * up, so there are no real logos to link to). Spring Boot serves that folder at
 * /images/logos/..., so they work offline and are stored like any pasted link.
 */
final class SampleCatalogData {

    record SampleProduct(String name, BigDecimal price, int stock, String imageUrl, String description) {
    }

    record SampleShop(int number, String shopName, String categoryName, String logoUrl,
                      List<SampleProduct> products) {
    }

    private SampleCatalogData() {
    }

    private static SampleProduct item(String name, String price, int stock, String imageUrl, String description) {
        return new SampleProduct(name, new BigDecimal(price), stock, imageUrl, description);
    }

    static final List<SampleShop> SHOPS = List.of(
        new SampleShop(1, "Spice Route Kitchenware", "Kitchen & Dining", "/images/logos/spice-route-kitchenware.svg", List.of(
                item("Bamboo Spatula", "2400.00", 8,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp",
                        "The Bamboo Spatula is a versatile kitchen tool made from eco-friendly bamboo."),
                item("Black Aluminium Cup", "1800.00", 15,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/thumbnail.webp",
                        "The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages."),
                item("Black Whisk", "3000.00", 22,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp",
                        "The Black Whisk is a kitchen essential for whisking and beating ingredients."),
                item("Boxed Blender", "12000.00", 29,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp",
                        "The Boxed Blender is a powerful and compact blender perfect for smoothies, shakes, and more."),
                item("Carbon Steel Wok", "9000.00", 36,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/thumbnail.webp",
                        "The Carbon Steel Wok is a versatile cooking pan suitable for stir-frying, saut\u00e9ing, and deep frying."),
                item("Chopping Board", "3900.00", 43,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/chopping-board/thumbnail.webp",
                        "The Chopping Board is an essential kitchen accessory for food preparation."),
                item("Citrus Squeezer Yellow", "2700.00", 10,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/citrus-squeezer-yellow/thumbnail.webp",
                        "The Citrus Squeezer in Yellow is a handy tool for extracting juice from citrus fruits."),
                item("Egg Slicer", "2100.00", 17,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp",
                        "The Egg Slicer is a convenient tool for slicing boiled eggs evenly."),
                item("Electric Stove", "15000.00", 24,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp",
                        "The Electric Stove provides a portable and efficient cooking solution."),
                item("Fine Mesh Strainer", "3000.00", 31,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/fine-mesh-strainer/thumbnail.webp",
                        "The Fine Mesh Strainer is a versatile tool for straining liquids and sifting dry ingredients."),
                item("Fork", "1200.00", 38,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/fork/thumbnail.webp",
                        "The Fork is a classic utensil for various dining and serving purposes."),
                item("Glass", "1500.00", 5,
                        "https://cdn.dummyjson.com/product-images/kitchen-accessories/glass/thumbnail.webp",
                        "The Glass is a versatile and elegant drinking vessel suitable for a variety of beverages."))),
        new SampleShop(2, "Lanka Fresh Grocers", "Groceries", "/images/logos/lanka-fresh-grocers.svg", List.of(
                item("Apple", "600.00", 11,
                        "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
                        "Fresh and crisp apples, perfect for snacking or incorporating into various recipes."),
                item("Beef Steak", "3900.00", 18,
                        "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
                        "High-quality beef steak, great for grilling or cooking to your preferred level of doneness."),
                item("Cat Food", "2700.00", 25,
                        "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
                        "Nutritious cat food formulated to meet the dietary needs of your feline friend."),
                item("Chicken Meat", "3000.00", 32,
                        "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
                        "Fresh and tender chicken meat, suitable for various culinary preparations."),
                item("Cooking Oil", "1500.00", 39,
                        "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
                        "Versatile cooking oil suitable for frying, saut\u00e9ing, and various culinary applications."),
                item("Cucumber", "450.00", 6,
                        "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp",
                        "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side."),
                item("Dog Food", "3300.00", 13,
                        "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp",
                        "Specially formulated dog food designed to provide essential nutrients for your canine companion."),
                item("Eggs", "900.00", 20,
                        "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
                        "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast."),
                item("Fish Steak", "4500.00", 27,
                        "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp",
                        "Quality fish steak, suitable for grilling, baking, or pan-searing."),
                item("Green Bell Pepper", "400.00", 34,
                        "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp",
                        "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes."),
                item("Green Chili Pepper", "300.00", 41,
                        "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp",
                        "Spicy green chili pepper, ideal for adding heat to your favorite recipes."),
                item("Honey Jar", "2100.00", 8,
                        "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
                        "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food."))),
        new SampleShop(3, "Kandy Sports Hub", "Sports & Outdoors", "/images/logos/kandy-sports-hub.svg", List.of(
                item("American Football", "6000.00", 14,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp",
                        "The American Football is a classic ball used in American football games."),
                item("Baseball Ball", "2700.00", 21,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp",
                        "The Baseball Ball is a standard baseball used in baseball games."),
                item("Baseball Glove", "7500.00", 28,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/thumbnail.webp",
                        "The Baseball Glove is a protective glove worn by baseball players."),
                item("Basketball", "4500.00", 35,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/thumbnail.webp",
                        "The Basketball is a standard ball used in basketball games."),
                item("Basketball Rim", "12000.00", 42,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp",
                        "The Basketball Rim is a sturdy hoop and net assembly mounted on a basketball backboard."),
                item("Cricket Ball", "3900.00", 9,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-ball/thumbnail.webp",
                        "The Cricket Ball is a hard leather ball used in the sport of cricket."),
                item("Cricket Bat", "9000.00", 16,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/thumbnail.webp",
                        "The Cricket Bat is an essential piece of cricket equipment used by batsmen to hit the cricket ball."),
                item("Cricket Helmet", "13500.00", 23,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/thumbnail.webp",
                        "The Cricket Helmet is a protective headgear worn by cricket players, especially batsmen and wicketkeepers."),
                item("Cricket Wicket", "9000.00", 30,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-wicket/thumbnail.webp",
                        "The Cricket Wicket is a set of three stumps and two bails, forming a wicket used in the sport of cricket."),
                item("Feather Shuttlecock", "1800.00", 37,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/feather-shuttlecock/thumbnail.webp",
                        "The Feather Shuttlecock is used in the sport of badminton."),
                item("Football", "5500.00", 44,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/football/thumbnail.webp",
                        "The Football, also known as a soccer ball, is the standard ball used in the sport of football (soccer)."),
                item("Golf Ball", "3000.00", 11,
                        "https://cdn.dummyjson.com/product-images/sports-accessories/golf-ball/thumbnail.webp",
                        "The Golf Ball is a small ball used in the sport of golf."))),
        new SampleShop(4, "Galle Mobile Point", "Phones & Tablets", "/images/logos/galle-mobile-point.svg", List.of(
                item("iPhone 5s", "60000.00", 17,
                        "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
                        "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release."),
                item("iPhone 6", "90000.00", 24,
                        "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
                        "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance."),
                item("iPhone 13 Pro", "330000.00", 31,
                        "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
                        "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display."),
                item("iPhone X", "270000.00", 38,
                        "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
                        "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance."),
                item("Oppo A57", "75000.00", 5,
                        "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
                        "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features."),
                item("Oppo F19 Pro Plus", "120000.00", 12,
                        "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
                        "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities."),
                item("Oppo K1", "90000.00", 19,
                        "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp",
                        "The Oppo K1 series offers a range of smartphones with various features and specifications."),
                item("Realme C35", "45000.00", 26,
                        "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
                        "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use."),
                item("Realme X", "90000.00", 33,
                        "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp",
                        "The Realme X is a mid-range smartphone known for its sleek design and impressive display."),
                item("iPad Mini 2021 Starlight", "150000.00", 40,
                        "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
                        "The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple."),
                item("Samsung Galaxy Tab S8 Plus Grey", "180000.00", 7,
                        "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
                        "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung."),
                item("Samsung Galaxy Tab White", "105000.00", 14,
                        "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp",
                        "The Samsung Galaxy Tab in White is a sleek and versatile Android tablet."))),
        new SampleShop(5, "Colombo Tech Corner", "Electronics & Accessories", "/images/logos/colombo-tech-corner.svg", List.of(
                item("Apple MacBook Pro 14 Inch Space Grey", "600000.00", 20,
                        "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
                        "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display."),
                item("Asus Zenbook Pro Dual Screen Laptop", "540000.00", 27,
                        "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
                        "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals."),
                item("Huawei Matebook X Pro", "420000.00", 34,
                        "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
                        "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go."),
                item("Lenovo Yoga 920", "330000.00", 41,
                        "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
                        "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability."),
                item("New DELL XPS 13 9300 Laptop", "450000.00", 8,
                        "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
                        "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks."),
                item("Amazon Echo Plus", "30000.00", 15,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
                        "The Amazon Echo Plus is a smart speaker with built-in Alexa voice control."),
                item("Apple Airpods", "39000.00", 22,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
                        "The Apple Airpods offer a seamless wireless audio experience."),
                item("Apple AirPods Max Silver", "165000.00", 29,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
                        "The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation."),
                item("Apple Airpower Wireless Charger", "24000.00", 36,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp",
                        "The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly."),
                item("Apple HomePod Mini Cosmic Grey", "30000.00", 43,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
                        "The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience."),
                item("Apple iPhone Charger", "6000.00", 10,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
                        "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone."),
                item("Apple MagSafe Battery Pack", "30000.00", 17,
                        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
                        "The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone."))),
        new SampleShop(6, "Gentleman's Row", "Men's Fashion", "/images/logos/gentlemans-row.svg", List.of(
                item("Blue & Black Check Shirt", "9000.00", 23,
                        "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
                        "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern."),
                item("Gigabyte Aorus Men Tshirt", "7500.00", 30,
                        "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
                        "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts."),
                item("Man Plaid Shirt", "10500.00", 37,
                        "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
                        "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern."),
                item("Nike Air Jordan 1 Red And Black", "45000.00", 44,
                        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
                        "The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes."),
                item("Nike Baseball Cleats", "24000.00", 11,
                        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
                        "Nike Baseball Cleats are designed for maximum traction and performance on the baseball field."),
                item("Puma Future Rider Trainers", "27000.00", 18,
                        "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
                        "The Puma Future Rider Trainers offer a blend of retro style and modern comfort."),
                item("Brown Leather Belt Watch", "27000.00", 25,
                        "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp",
                        "The Brown Leather Belt Watch is a stylish timepiece with a classic design."),
                item("Longines Master Collection", "450000.00", 32,
                        "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp",
                        "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship."),
                item("Rolex Cellini Date Black Dial", "2700000.00", 39,
                        "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp",
                        "The Rolex Cellini Date with Black Dial is a classic and prestigious watch."),
                item("Black Sun Glasses", "9000.00", 6,
                        "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
                        "The Black Sun Glasses are a classic and stylish choice, featuring a sleek black frame and tinted lenses."),
                item("Classic Sun Glasses", "7500.00", 13,
                        "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
                        "The Classic Sun Glasses offer a timeless design with a neutral frame and UV-protected lenses."),
                item("Green and Black Glasses", "10500.00", 20,
                        "https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp",
                        "The Green and Black Glasses feature a bold combination of green and black colors, adding a touch of vibrancy to your eyewear collection."))),
        new SampleShop(7, "Lotus Boutique", "Women's Fashion", "/images/logos/lotus-boutique.svg", List.of(
                item("Black Women's Gown", "39000.00", 26,
                        "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
                        "The Black Women's Gown is an elegant and timeless evening gown."),
                item("Corset Leather With Skirt", "27000.00", 33,
                        "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
                        "The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt."),
                item("Corset With Black Skirt", "24000.00", 40,
                        "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp",
                        "The Corset With Black Skirt is a chic and versatile outfit that pairs a fashionable corset with a classic black skirt."),
                item("Blue Frock", "9000.00", 7,
                        "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
                        "The Blue Frock is a charming and stylish dress for various occasions."),
                item("Girl Summer Dress", "6000.00", 14,
                        "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
                        "The Girl Summer Dress is a cute and breezy dress designed for warm weather."),
                item("Gray Dress", "10500.00", 21,
                        "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
                        "The Gray Dress is a versatile and chic option for various occasions."),
                item("Black & Brown Slipper", "6000.00", 28,
                        "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp",
                        "The Black & Brown Slipper is a comfortable and stylish choice for casual wear."),
                item("Calvin Klein Heel Shoes", "24000.00", 35,
                        "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp",
                        "Calvin Klein Heel Shoes are elegant and sophisticated, designed for formal occasions."),
                item("Golden Shoes Woman", "15000.00", 42,
                        "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp",
                        "The Golden Shoes for Women are a glamorous choice for special occasions."),
                item("Blue Women's Handbag", "15000.00", 9,
                        "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
                        "The Blue Women's Handbag is a stylish and spacious accessory for everyday use."),
                item("Heshe Women's Leather Bag", "39000.00", 16,
                        "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp",
                        "The Heshe Women's Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman."),
                item("Prada Women Bag", "180000.00", 23,
                        "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
                        "The Prada Women Bag is an iconic designer bag that exudes elegance and luxury."))),
        new SampleShop(8, "Ceylon Glow Beauty", "Beauty & Personal Care", "/images/logos/ceylon-glow-beauty.svg", List.of(
                item("Essence Mascara Lash Princess", "3000.00", 29,
                        "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
                        "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects."),
                item("Eyeshadow Palette with Mirror", "6000.00", 36,
                        "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
                        "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks."),
                item("Powder Canister", "4500.00", 43,
                        "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
                        "The Powder Canister is a finely milled setting powder designed to set makeup and control shine."),
                item("Calvin Klein CK One", "15000.00", 10,
                        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
                        "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent."),
                item("Chanel Coco Noir Eau De", "39000.00", 17,
                        "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
                        "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood."),
                item("Dior J'adore", "27000.00", 24,
                        "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
                        "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine."),
                item("Attitude Super Leaves Hand Soap", "2700.00", 31,
                        "https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/thumbnail.webp",
                        "Attitude Super Leaves Hand Soap is a natural and nourishing hand soap enriched with the goodness of super leaves."),
                item("Olay Ultra Moisture Shea Butter Body Wash", "3900.00", 38,
                        "https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/thumbnail.webp",
                        "Olay Ultra Moisture Shea Butter Body Wash is a luxurious body wash that hydrates and nourishes your skin with the moisturizing power of shea butter."),
                item("Vaseline Men Body and Face Lotion", "3000.00", 5,
                        "https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp",
                        "Vaseline Men Body and Face Lotion is a specially formulated lotion designed to provide long-lasting moisture to men's skin."),
                item("Green Crystal Earring", "9000.00", 12,
                        "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp",
                        "The Green Crystal Earring is a dazzling accessory that features a vibrant green crystal."),
                item("Green Oval Earring", "7500.00", 19,
                        "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
                        "The Green Oval Earring is a stylish and versatile accessory with a unique oval shape."),
                item("Tropical Earring", "6000.00", 26,
                        "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/thumbnail.webp",
                        "The Tropical Earring is a fun and playful accessory inspired by tropical elements."))),
        new SampleShop(9, "Teak & Clay Home Living", "Home & Furniture", "/images/logos/teak-and-clay-home-living.svg", List.of(
                item("Annibale Colombo Bed", "570000.00", 32,
                        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
                        "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom."),
                item("Annibale Colombo Sofa", "750000.00", 39,
                        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
                        "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room."),
                item("Bedside Table African Cherry", "90000.00", 6,
                        "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
                        "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance."),
                item("Knoll Saarinen Executive Conference Chair", "150000.00", 13,
                        "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
                        "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design."),
                item("Wooden Bathroom Sink With Mirror", "240000.00", 20,
                        "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
                        "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror."),
                item("Decoration Swing", "18000.00", 27,
                        "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
                        "The Decoration Swing is a charming addition to your home decor."),
                item("Family Tree Photo Frame", "9000.00", 34,
                        "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp",
                        "The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories."),
                item("House Showpiece Plant", "12000.00", 41,
                        "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp",
                        "The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance."),
                item("Plant Pot", "4500.00", 8,
                        "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp",
                        "The Plant Pot is a stylish container for your favorite plants."),
                item("Table Lamp", "15000.00", 15,
                        "https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp",
                        "The Table Lamp is a functional and decorative lighting solution for your living space.")))
    );
}
